services:
  airportAPI:
    image: your_name/airport_api:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://aws_stuff/airport_db
      - spring.datasource.username=admin
      - spring.datasource.password=adminpassword
  #airportWeb:
    #Frontend stuff goes here methinks...?