services:
  airportAPI:
    image: joeyjowhi/airport_api:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://airport-db.cpi4sgc6w6oe.us-east-1.rds.amazonaws.com:3306/airport
      - spring.datasource.username=admin
      - spring.datasource.password=adminpassword